[floor_friction_partial_dfr_dx_custom_gd_func, floor_friction_partial_dfr_dfn_custom_gd_func, ...
    floor_friction_g1_partial_dfr_dx_custom_gd_func, floor_friction_g1_partial_dfr_dfn_custom_gd_func] = ...
    generateFloorFrictionJacobianFunctions()